[project]
name = "sidechain-service"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.sidechain-admin]
path = "contracts/sidechain-admin.clar"
depends_on = []

[contracts.validator-registry]
path = "contracts/validator-registry.clar"
depends_on = []

[contracts.node-verification]
path = "contracts/node-verification.clar"
depends_on = []

[contracts.reward-mechanism]
path = "contracts/reward-mechanism.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
